# emu config
# emu: bluestack 
emu: mumu
# adbPort: 

mainStory:
  # enable: true
  enable: false

areaExploration:
  # enable: true
  enable: false

monsterStory:
  # enable: true
  enable: false

fishing:
  enable: true
  # enable: false

# pvp
# every 30 minutes
# look for quick match
# 10 times

# Path of growth
# 6 times per day
# reset with crystal

resetAt: 00:00

tasks:
- challengeArena:
    enable: false

- repeatQuest:
    enable: false
    resetWithCrystalPerDay: 2
    map: rudelin # tesca, ayah, flurence, rukurangma, kontana
    rewardTicket: pathOfGrowth # essenceDungeon, challengeArena

# - brawlArena:
#     enable: true
#     times: 5

# energy - HP
# guard  - DEF
# blade  - CRI rate
# rage   - CRI dmg
# fatal  - ATK
# swift  - ATK SPD
# focus  - Acc
# endure - RES
# foresight - Evasion
# assemble - Precision

- runeCombination:
    enable: true
    Cooldown: 60m
    steps:
      # - runeSet: [foresight, swift] # ensure mixes
      #   stars: 4
      - runeSet: [swift] # ensure mixes
        stars: 4
      - runeSet: [foresight] # ensure mixes
        stars: 4
      - runeSet: [endure, assemble] # ensure mixes
        stars: 4
      - runeSet: [blade]
        stars: 4
      - runeSet: [rage]
        stars: 4
      - runeSet: [energy]
        stars: 4
      - runeSet: [guard]
        stars: 4
      - runeSet: [fatal]
        stars: 4
      - runeSet: [focus]
        stars: 4

- autoFarm:
    # enable: false
    enable: true
    # black_ash_harpu
    miniBoss: black_ash_harpu
    interval: 11s

