Names:
  auto_farm:
    LastMoving: "2023-05-28T13:28:16.1318747+07:00"
    NextExecution: "2023-05-28T13:28:51.2842025+07:00"
    NextReset: "0001-01-01T00:00:00Z"
    State: 9999
  challenge_arena:
    LastExecuted: "0001-01-01T00:00:00Z"
    Name: challenge_arena
    NextExecution: "2023-07-04T22:38:33.7337541+07:00"
    NextReset: "2023-07-05T00:00:00+07:00"
    PointIdx: 1
    Points:
    - X: 591
      "Y": 86
    Repeat: 3
    State: 9999
    Stats:
    - Date: "2023-07-04T00:00:00+07:00"
      QuickBattle: 2
      Refresh: 1
    - Date: "2023-05-28T00:00:00+07:00"
      QuickBattle: 0
      Refresh: 2
    - Date: "2023-05-28T00:00:00+07:00"
      QuickBattle: 28
      Refresh: 21
    - Date: "2023-05-28T00:00:00+07:00"
      QuickBattle: 0
      Refresh: 1
    - Date: "2023-05-26T00:00:00+07:00"
      QuickBattle: 1
      Refresh: 1
    - Date: "2023-05-25T00:00:00+07:00"
      QuickBattle: 2
      Refresh: 2
    - Date: "2023-05-24T00:00:00+07:00"
      QuickBattle: 6
      Refresh: 8
    - Date: "2023-05-24T00:00:00+07:00"
      QuickBattle: 1
      Refresh: 3
    - Date: "2023-05-24T00:00:00+07:00"
      QuickBattle: 0
      Refresh: 1
    - Date: "2023-05-24T00:00:00+07:00"
      QuickBattle: 0
      Refresh: 0
    - Date: "2023-05-24T00:00:00+07:00"
      QuickBattle: 7
      Refresh: 6
    - Date: "2023-05-23T00:00:00+07:00"
      QuickBattle: 0
      Refresh: 1
    - Date: "2023-05-23T00:00:00+07:00"
      QuickBattle: 25
      Refresh: 18
    - Date: "2023-05-23T00:00:00+07:00"
      QuickBattle: 0
      Refresh: 1
    - Date: "2023-05-23T00:00:00+07:00"
      QuickBattle: 0
      Refresh: 0
    - Date: "2023-05-19T00:00:00+07:00"
      QuickBattle: 0
      Refresh: 0
    - Date: "2023-05-19T00:00:00+07:00"
      QuickBattle: 7
      Refresh: 5
    - Date: "2023-05-19T00:00:00+07:00"
      QuickBattle: 0
      Refresh: 0
    - Date: "2023-05-19T00:00:00+07:00"
      QuickBattle: 0
      Refresh: 0
    - Date: "2023-05-19T00:00:00+07:00"
      QuickBattle: 0
      Refresh: 0
    - Date: "2023-05-19T00:00:00+07:00"
      QuickBattle: 3
      Refresh: 2
    - Date: "2023-05-17T00:00:00+07:00"
      QuickBattle: 26
      Refresh: 13
    - Date: "2023-05-15T10:00:00+07:00"
      QuickBattle: 21
      Refresh: 17
    - Date: "2023-05-13T19:00:00+07:00"
      QuickBattle: 20
      Refresh: 16
    - Date: "2023-05-09T12:00:00+07:00"
      QuickBattle: 20
      Refresh: 17
    - Date: "2023-05-08T10:00:00+07:00"
      QuickBattle: 18
      Refresh: 16
    - Date: "2023-05-07T05:00:00+07:00"
      QuickBattle: 19
      Refresh: 21
    - Date: "2023-05-04T21:00:00+07:00"
      QuickBattle: 34
      Refresh: 21
  rune_combination:
    CurrentRuneSet: rage
    CurrentStars: 4
    LastRuneSet: rage
    LastStars: 4
    NextExecution: "2023-05-28T14:11:14.9530821+07:00"
    NextReset: "2023-05-29T00:00:00+07:00"
    RuneChoices: null
    RuneCount: 0
    RuneLimit:
      rage: 3
    RunesCount:
      assemble: 2
      blade: 1
      despair: 1
      destroy: 3
      endure: 0
      energy: 1
      fatal: 1
      focus: 2
      foresight: 0
      guard: 2
      rage: 1
      shield: 0
      swift: 2
      vampire: 4
    State: 0
    Stats:
    - CombineCount: 537
      Date: "2023-05-28T00:00:00+07:00"
      FiveStarRunes: 49
      FourStarRunes: 487
      SixStarRunes: 0
    - CombineCount: 3
      Date: "2023-05-26T00:00:00+07:00"
      FiveStarRunes: 1
      FourStarRunes: 1
      SixStarRunes: 0
    - CombineCount: 31
      Date: "2023-05-25T00:00:00+07:00"
      FiveStarRunes: 1
      FourStarRunes: 30
      SixStarRunes: 0
    - CombineCount: 767
      Date: "2023-05-24T00:00:00+07:00"
      FiveStarRunes: 77
      FourStarRunes: 685
      SixStarRunes: 0
    - CombineCount: 575
      Date: "2023-05-23T00:00:00+07:00"
      FiveStarRunes: 47
      FourStarRunes: 422
      SixStarRunes: 0
    - CombineCount: 27
      Date: "2023-05-19T00:00:00+07:00"
      FiveStarRunes: 0
      FourStarRunes: 0
      SixStarRunes: 0
    - CombineCount: 471
      Date: "2023-05-18T00:00:00+07:00"
      FiveStarRunes: 54
      FourStarRunes: 416
      SixStarRunes: 0
    - CombineCount: 296
      Date: "2023-05-17T00:00:00+07:00"
      FiveStarRunes: 38
      FourStarRunes: 256
      SixStarRunes: 0
    - CombineCount: 1190
      Date: "2023-05-16T00:00:00+07:00"
      FiveStarRunes: 112
      FourStarRunes: 1076
      SixStarRunes: 0
    - CombineCount: 900
      Date: "2023-05-15T00:00:00+07:00"
      FiveStarRunes: 83
      FourStarRunes: 815
      SixStarRunes: 0
    - CombineCount: 227
      Date: "2023-05-14T00:00:00+07:00"
      FiveStarRunes: 25
      FourStarRunes: 202
      SixStarRunes: 0
    - CombineCount: 185
      Date: "2023-05-13T00:00:00+07:00"
      FiveStarRunes: 14
      FourStarRunes: 170
      SixStarRunes: 0
    - CombineCount: 357
      Date: "2023-05-11T00:00:00+07:00"
      FiveStarRunes: 44
      FourStarRunes: 312
      SixStarRunes: 0
    - CombineCount: 927
      Date: "2023-05-10T00:00:00+07:00"
      FiveStarRunes: 89
      FourStarRunes: 832
      SixStarRunes: 0
    - CombineCount: 895
      Date: "2023-05-09T00:00:00+07:00"
      FiveStarRunes: 96
      FourStarRunes: 796
      SixStarRunes: 0
    - CombineCount: 840
      Date: "2023-05-08T00:00:00+07:00"
      FiveStarRunes: 90
      FourStarRunes: 749
      SixStarRunes: 0
    - CombineCount: 532
      Date: "2023-05-07T00:00:00+07:00"
      FiveStarRunes: 53
      FourStarRunes: 476
      SixStarRunes: 0
    - CombineCount: 294
      Date: "2023-05-06T00:00:00+07:00"
      FiveStarRunes: 31
      FourStarRunes: 261
      SixStarRunes: 0
    - CombineCount: 335
      Date: "2023-05-05T00:00:00+07:00"
      FiveStarRunes: 29
      FourStarRunes: 303
      SixStarRunes: 0
    - CombineCount: 654
      Date: "2023-05-03T00:00:00+07:00"
      FiveStarRunes: 60
      FourStarRunes: 592
      SixStarRunes: 0
    - CombineCount: 492
      Date: "2023-05-02T00:00:00+07:00"
      FiveStarRunes: 43
      FourStarRunes: 448
      SixStarRunes: 0
    - CombineCount: 589
      Date: "2023-05-01T00:00:00+07:00"
      FiveStarRunes: 44
      FourStarRunes: 543
      SixStarRunes: 0
    - CombineCount: 338
      Date: "2023-04-29T00:00:00+07:00"
      FiveStarRunes: 34
      FourStarRunes: 304
      SixStarRunes: 0
    - CombineCount: 559
      Date: "2023-04-28T00:00:00+07:00"
      FiveStarRunes: 57
      FourStarRunes: 500
      SixStarRunes: 0
    - CombineCount: 449
      Date: "2023-04-27T00:00:00+07:00"
      FiveStarRunes: 45
      FourStarRunes: 398
      SixStarRunes: 0
    - CombineCount: 234
      Date: "2023-04-26T07:00:00+07:00"
      FiveStarRunes: 32
      FourStarRunes: 200
      SixStarRunes: 0
    StepIdx: 0
tasks:
- LastExecuted: "0001-01-01T00:00:00Z"
  Name: challenge_arena
  NextExecuted: "2023-04-25T07:35:20.7367293+07:00"
  NextReset: "2023-04-26T00:00:00+07:00"
  PointIdx: 1
  Points:
  - X: 591
    "Y": 86
  - X: 591
    "Y": 340
  - X: 591
    "Y": 467
  Repeat: 1
  Stats:
  - Date: "2023-04-25T00:00:00+07:00"
    QuickBattle: 24
    Refresh: 14
  - Date: "2023-04-24T00:00:00+07:00"
    QuickBattle: 20
    Refresh: 8
  - Date: "2023-04-23T00:00:00+07:00"
    QuickBattle: 12
    Refresh: 8
- null
